name: Build & Test

on:
  push:
    branches: [ master, developing ]
  pull_request:
    branches: [ master, developing ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
      - uses: actions/checkout@v2.4.0
        name: Checkout
      - run: sudo apt update && sudo apt install g++-11
        name: Install g++-11
      - run: sudo apt-get install libbenchmark-dev
        name: Install Google Benchmark
      - run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=g++-11
        name: Configure CMake
      - run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target Test
        name: Build project
      - working-directory: ${{github.workspace}}/build
        run: ./Test
        name: Run tests
